import type { Brain, SourceAnswer } from "./schema";

/**
 * Maya's deep-dive answers, lightly cleaned transcripts. The cards below quote them; observeEngine
 * reads them to diagnose how she talks (scenes, mostly, whatever the quiz said).
 */
const SAMPLE_ANSWERS: SourceAnswer[] = [
  { id: "a_s1_1", questionId: "s1_1", date: "2026-08-01", text: "Jo rang me from the car park after her second interview. She'd got the job. She said 'I didn't think I was allowed to want something else.' That's the whole thing, really. What changed for her is she stopped waiting for permission." },
  { id: "a_s1_2", questionId: "s1_2", date: "2026-08-01", text: "Three in the morning, bay four. I sat down on the floor of the sluice room and couldn't get up. Priya found me. She didn't say anything, she just sat down too. I handed my notice in nine days later." },
  { id: "a_s1_3", questionId: "s1_3", date: "2026-08-01", text: "I joined the wrong Zoom call. It was a careers workshop for a completely different trust. I stayed. Twenty minutes in I was answering questions for people I'd never met, and the host asked if I'd run one." },
  { id: "a_s1_4", questionId: "s1_4", date: "2026-08-02", text: "Twelve years in ICU. I loved it, I want to be really clear about that. People assume I left because I hated it. I left because I loved it and it was still killing me." },
  { id: "a_s1_5", questionId: "s1_5", date: "2026-08-02", text: "March. Zero bookings. I applied for a bank shift and sat in the car outside the hospital and didn't go in. My partner said 'you're allowed to go back, you know.' I didn't. Two weeks later Jo booked." },
  { id: "a_s2_1", questionId: "s2_1", date: "2026-08-03", text: "Burnout is a system design outcome. I'll say that until I'm blue in the face. Nobody burns out because they're weak, they burn out because the rota was built to break them." },
  { id: "a_s2_2", questionId: "s2_2", date: "2026-08-03", text: "Everyone says nurses have transferable skills. It's a lie we tell people on the way out of the door. The skills transfer. The confidence doesn't, and nobody talks about that part." },
  { id: "a_s2_3", questionId: "s2_3", date: "2026-08-03", text: "You're allowed to want something else. I say it on every single call. The first thing I ask is who told you that you weren't." },
  { id: "a_s2_4", questionId: "s2_4", date: "2026-08-03", text: "Wellbeing webinars. If your answer to a broken rota is a webinar about resilience, you are the problem. The NHS treats burnout as a personal failing and it should be treated as a design fault." },
  { id: "a_s3_1", questionId: "s3_1", date: "2026-08-04", text: "Grew up in Bradford, above my dad's shop. I'm in Leeds now, three streets from the hospital, which I didn't plan and can't quite leave." },
  { id: "a_s3_2", questionId: "s3_2", date: "2026-08-04", text: "Me, Sam, and Bramble, who is a spaniel and a disgrace. Last week Bramble found a dead pigeon and brought it to a client call. I was on camera. The client has booked again, so." },
  { id: "a_s3_3", questionId: "s3_3", date: "2026-08-05", text: "People say I make them feel like it's allowed. Thirty-one nurses into new roles in fourteen months. I keep a list. Twelve stayed in healthcare, nineteen didn't." },
];

/**
 * A realistic fake brain for phase 1. Maya is invented.
 * Dates are relative to October 2026 so the heat map shows a spread of fresh / fading / quiet.
 */
export const sampleBrain: Brain = {
  id: "brain_maya",
  ownerName: "Maya Reid",
  goal: "growing_audience",
  enginePrimary: "storyteller",
  engineSecondary: "commentator",
  mix: { top: 50, middle: 40, bottom: 10 },
  cadencePerWeek: 3,
  // The quiz said teacher. Her answers (below) say storyteller; observed is derived from them at load.
  quiz: {
    blend: { teacher: 40, commentator: 28, documenter: 24, storyteller: 8 },
    primary: "teacher",
    secondary: "commentator",
    situation: "growing_audience",
    mix: { top: 50, middle: 40, bottom: 10 },
    cadencePerWeek: 3,
    quizFlag:
      "You scored yourself as a teacher, but nearly a third of you is commentator. Teachers who hide their opinions end up sounding like a textbook. Let the judgement show.",
    takenAt: "2026-07-30",
  },
  headline:
    "I help nurses who've burnt out build a second career without starting from zero. Ex-ICU, now a coach, still terrible at sitting still.",
  headlineOptions: [
    "I help nurses who've burnt out build a second career without starting from zero. Ex-ICU, now a coach, still terrible at sitting still.",
    "Twelve years in ICU, then a car park phone call. Now I help burnt-out nurses find the next thing without throwing the first thing away.",
    "Career coach for nurses who've had enough. Not of nursing, of the rota.",
  ],
  deepDiveStatus: "approved",
  sittingsDone: 3,
  events: [{ date: "2026-10-14", title: "Speaking at the Leeds nursing careers fair" }],
  answers: SAMPLE_ANSWERS,
  cards: [
    // Whys
    {
      id: "c_why_int",
      regionKey: "whys",
      kind: "why_internal",
      title: "The kid who organised the street",
      body: "I was the one who organised the rounders games on our street. Teams, rules, who was goalie. I'd forgotten that until you asked. I think I've always needed to be the one who makes the thing happen.",
      angles: ["childhood instinct", "the organiser", "what a job couldn't give me"],
      keywords: ["rounders", "street", "organised", "kid", "childhood", "teams"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-02",
    },
    {
      id: "c_why_ext",
      regionKey: "whys",
      kind: "why_external",
      title: "Jo's second interview",
      body: "Jo rang me from the car park after her second interview. She'd got the job. She said 'I didn't think I was allowed to want something else.' That's the whole thing, really.",
      angles: ["allowed to want", "the car park call", "what changes for them"],
      keywords: ["jo", "interview", "car park", "allowed", "want", "job"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-02",
    },
    {
      id: "c_why_phil",
      regionKey: "whys",
      kind: "why_philosophical",
      title: "Burnout isn't a personal failing",
      body: "Burnout is a system design outcome. I'll say that until I'm blue in the face. Nobody burns out because they're weak, they burn out because the rota was built to break them.",
      angles: ["system not person", "the rota", "what I'd change tomorrow"],
      keywords: ["burnout", "system", "rota", "failing", "weak", "design"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "middle",
      approvedAt: "2026-08-02",
    },
    // Stories
    {
      id: "c_story_start",
      regionKey: "stories",
      kind: "story",
      title: "The night shift I didn't finish",
      body: "Three in the morning, bay four. I sat down on the floor of the sluice room and couldn't get up. Priya found me. She didn't say anything, she just sat down too. I handed my notice in nine days later.",
      angles: ["the sluice room floor", "Priya sitting down", "nine days", "what I'd tell myself then"],
      keywords: ["night shift", "sluice", "floor", "priya", "notice", "three in the morning", "bay four"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-03",
    },
    {
      id: "c_story_luck",
      regionKey: "stories",
      kind: "story",
      title: "The wrong Zoom link",
      body: "I joined the wrong Zoom call. It was a careers workshop for a completely different trust. I stayed. Twenty minutes in I was answering questions for people I'd never met, and the host asked if I'd run one.",
      angles: ["the accident", "staying when you should leave", "the first workshop"],
      keywords: ["zoom", "wrong link", "workshop", "trust", "accident", "host"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-03",
    },
    {
      id: "c_story_before",
      regionKey: "stories",
      kind: "story",
      title: "Twelve years in ICU",
      body: "Twelve years. I loved it, I want to be really clear about that. People assume I left because I hated it. I left because I loved it and it was still killing me.",
      angles: ["I loved it", "leaving something you love", "what twelve years teaches you"],
      keywords: ["icu", "twelve years", "loved", "leaving", "nurse", "nursing"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-03",
    },
    {
      id: "c_story_hard",
      regionKey: "stories",
      kind: "story",
      title: "The month with no clients",
      body: "March. Zero bookings. I applied for a bank shift and sat in the car outside the hospital and didn't go in. My partner said 'you're allowed to go back, you know.' I didn't. Two weeks later Jo booked.",
      angles: ["sitting in the car", "allowed to go back", "the two weeks", "what nearly broke"],
      keywords: ["march", "zero bookings", "bank shift", "car", "hospital", "partner", "allowed"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-05",
    },
    // Opinions
    {
      id: "c_op_1",
      regionKey: "opinions",
      kind: "opinion",
      title: "Transferable skills is a lie we tell nurses",
      body: "Everyone says 'nurses have so many transferable skills'. Nobody tells them how to transfer them. It's like handing someone a passport and no plane.",
      angles: ["passport and no plane", "the advice that stops short", "what transferring actually looks like"],
      keywords: ["transferable", "skills", "passport", "plane", "advice"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "middle",
      approvedAt: "2026-08-06",
    },
    {
      id: "c_op_2",
      regionKey: "opinions",
      kind: "opinion",
      title: "Resilience training is gaslighting",
      body: "If your solution to a broken rota is a resilience webinar, you're not fixing anything, you're teaching people to tolerate it.",
      angles: ["the webinar", "tolerate vs fix", "what managers could do instead"],
      keywords: ["resilience", "webinar", "training", "tolerate", "rota", "managers"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "middle",
      approvedAt: "2026-08-06",
    },
    {
      id: "c_op_3",
      regionKey: "opinions",
      kind: "opinion",
      title: "Leaving isn't quitting",
      body: "I get told I 'left nursing'. I didn't. I still think like a nurse every single day. Leaving the ward isn't leaving the profession.",
      angles: ["still a nurse", "the ward vs the profession", "what I kept"],
      keywords: ["leaving", "quitting", "ward", "profession", "still a nurse"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "middle",
      approvedAt: "2026-08-06",
    },
    {
      id: "c_op_4",
      regionKey: "opinions",
      kind: "opinion",
      title: "Notice periods should be sabbaticals",
      body: "Trusts lose people forever because the only exit is the door. Give someone three months out and half of them would come back.",
      angles: ["the only exit is the door", "three months out", "who would come back"],
      keywords: ["notice", "sabbatical", "trusts", "exit", "come back"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "middle",
      approvedAt: "2026-08-06",
    },
    {
      id: "c_op_reserve",
      regionKey: "opinions",
      kind: "opinion_reserve",
      title: "Reserve: trusts should fund the coaching",
      body: "Held back for when the employer offer exists.",
      angles: [],
      keywords: ["employer", "fund", "coaching"],
      isLane: false,
      constructed: true,
      privacy: "on_board",
      funnelDefault: "bottom",
    },
    // Personality furniture
    {
      id: "c_f_1",
      regionKey: "personality",
      kind: "furniture",
      title: "Grew up in Grimsby, now in Sheffield",
      body: "Grimsby. Fish, wind, honest people. Sheffield now, which is hills and the same honesty.",
      angles: [],
      keywords: ["grimsby", "sheffield", "hills"],
      isLane: false,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-07",
    },
    {
      id: "c_f_2",
      regionKey: "personality",
      kind: "signature",
      title: "Bramble the lurcher",
      body: "Bramble. She's a lurcher and she's an idiot and I love her more than most people. She's in half my photos and I'm not sorry.",
      angles: ["the dog in the photos", "walks where the ideas come from"],
      keywords: ["bramble", "lurcher", "dog", "walk"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-07",
    },
    {
      id: "c_f_3",
      regionKey: "personality",
      kind: "furniture",
      title: "Terrible at sitting still",
      body: "My family would say I'm obsessed with lists and incapable of a lie-in. Both true.",
      angles: [],
      keywords: ["lists", "lie-in", "still"],
      isLane: false,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-07",
    },
    {
      id: "c_f_4",
      regionKey: "personality",
      kind: "furniture",
      title: "Studied biochemistry first",
      body: "Biochem degree before nursing. It still shows up: I want the mechanism, not the vibe.",
      angles: [],
      keywords: ["biochemistry", "degree", "mechanism"],
      isLane: false,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "top",
      approvedAt: "2026-08-07",
    },
    // Receipts
    {
      id: "c_r_1",
      regionKey: "receipts",
      kind: "receipt_number",
      title: "31 nurses into new roles in 14 months",
      body: "Thirty-one. I keep a list. Twelve stayed in healthcare, nineteen didn't.",
      angles: ["the list", "twelve stayed"],
      keywords: ["31", "thirty-one", "roles", "months", "list"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "bottom",
      approvedAt: "2026-08-08",
    },
    {
      id: "c_r_2",
      regionKey: "receipts",
      kind: "receipt_quote",
      title: "\"You gave me permission\"",
      body: "That's the phrase that comes up most in the messages. Permission. I've got a folder of them.",
      angles: ["the folder", "permission"],
      keywords: ["permission", "messages", "folder"],
      isLane: true,
      constructed: false,
      privacy: "on_board",
      funnelDefault: "bottom",
      approvedAt: "2026-08-08",
    },
    // Engine
    {
      id: "c_engine",
      regionKey: "engine",
      kind: "furniture",
      title: "Storyteller, Commentator second",
      body: "Answers every question with a scene. Remembers dialogue. Gets energised when something in the industry annoys her.",
      angles: [],
      keywords: [],
      isLane: false,
      constructed: true,
      privacy: "on_board",
      funnelDefault: "top",
    },
  ],
  posts: [
    { id: "p1", status: "posted", body: "Three in the morning, bay four…", funnelLevel: "top", laneCardIds: ["c_story_start"], postedAt: "2026-10-02" },
    { id: "p2", status: "posted", body: "Everyone says nurses have transferable skills…", funnelLevel: "middle", laneCardIds: ["c_op_1"], postedAt: "2026-09-30" },
    { id: "p3", status: "posted", body: "Bramble found a dead pigeon…", funnelLevel: "top", laneCardIds: ["c_f_2"], postedAt: "2026-09-28" },
    { id: "p4", status: "posted", body: "Twelve years in ICU…", funnelLevel: "top", laneCardIds: ["c_story_before"], postedAt: "2026-09-25" },
    { id: "p5", status: "posted", body: "If your answer to a broken rota is a webinar…", funnelLevel: "middle", laneCardIds: ["c_op_2"], postedAt: "2026-09-23" },
    { id: "p6", status: "posted", body: "Bay four, again…", funnelLevel: "top", laneCardIds: ["c_story_start"], postedAt: "2026-09-19" },
    { id: "p7", status: "posted", body: "Thirty-one nurses…", funnelLevel: "bottom", laneCardIds: ["c_r_1"], postedAt: "2026-09-16" },
    { id: "p8", status: "posted", body: "The sluice room floor…", funnelLevel: "top", laneCardIds: ["c_story_start"], postedAt: "2026-09-12" },
    { id: "p9", status: "posted", body: "Transferable skills, part two…", funnelLevel: "middle", laneCardIds: ["c_op_1"], postedAt: "2026-09-09" },
    { id: "p10", status: "posted", body: "Burnout is a system outcome…", funnelLevel: "middle", laneCardIds: ["c_why_phil"], postedAt: "2026-08-20" },
    { id: "p11", status: "posted", body: "I joined the wrong Zoom…", funnelLevel: "top", laneCardIds: ["c_story_luck"], postedAt: "2026-08-14" },
    { id: "p12", status: "posted", body: "The street rounders games…", funnelLevel: "top", laneCardIds: ["c_why_int"], postedAt: "2026-08-05" },
  ],
};
